(()=>{'use strict';const CONTROL_KEYS=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','a','d','w','s',' ','Spacebar'];function releaseControls(){for(const key of CONTROL_KEYS){const code=key===' '?'Space':key.startsWith('Arrow')?key:'';const ev=new KeyboardEvent('keyup',{key,code,bubbles:true});document.dispatchEvent(ev);window.dispatchEvent(ev)}}function pauseSupported(){if(document.hidden){const b=document.getElementById('pause');if(b&&!b.disabled&&b.offsetParent!==null&&!/resume/i.test(b.textContent||'')){try{b.click()}catch(e){}}}}function ready(){document.documentElement.classList.add('nd-polish-ready');document.body?.setAttribute('data-nd-quality','3');const title=(document.querySelector('h1')?.textContent||document.title||'Neon District game').trim();document.querySelectorAll('button').forEach(b=>{if(!b.getAttribute('aria-label')&&(b.textContent||'').trim())b.setAttribute('aria-label',(b.textContent||'').trim())});document.querySelectorAll('canvas').forEach(cv=>{cv.setAttribute('role','img');if(!cv.getAttribute('aria-label'))cv.setAttribute('aria-label',title+' game area');cv.addEventListener('contextmenu',e=>e.preventDefault())})}window.addEventListener('blur',releaseControls);window.addEventListener('pagehide',releaseControls);document.addEventListener('visibilitychange',()=>{releaseControls();pauseSupported()});window.addEventListener('pointercancel',releaseControls,true);window.addEventListener('error',()=>{if(document.querySelector('.nd-error-toast'))return;const el=document.createElement('div');el.className='nd-error-toast';el.textContent='Game error detected — reload this game if controls stop responding.';document.body?.appendChild(el);setTimeout(()=>el.remove(),3200)});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready()
function stage(){return document.querySelector('.stage')||document.querySelector('canvas')?.parentElement||document.body}
function pop(el){if(!el)return;el.classList.remove('nd-pop');void el.offsetWidth;el.classList.add('nd-pop');setTimeout(()=>el.classList.remove('nd-pop'),280)}
function shake(){const el=stage();if(!el)return;el.classList.remove('nd-shake');void el.offsetWidth;el.classList.add('nd-shake');setTimeout(()=>el.classList.remove('nd-shake'),300)}
function flash(){const el=stage();if(!el)return;el.classList.remove('nd-flash');void el.offsetWidth;el.classList.add('nd-flash');setTimeout(()=>el.classList.remove('nd-flash'),220)}
window.NDPolish={pop,shake,flash};
document.addEventListener('pointerdown',e=>{const b=e.target.closest?.('button');if(b)b.classList.add('nd-pressed');const st=e.target.closest?.('.stage');if(st)st.classList.add('nd-stage-active')},true);
for(const ev of ['pointerup','pointercancel'])document.addEventListener(ev,()=>{document.querySelectorAll('.nd-pressed').forEach(x=>x.classList.remove('nd-pressed'));document.querySelectorAll('.nd-stage-active').forEach(x=>x.classList.remove('nd-stage-active'))},true);
document.addEventListener('keydown',e=>{if((e.code==='Space'||e.code==='Enter')&&e.target?.tagName==='BUTTON')e.target.classList.add('nd-pressed')},true);
document.addEventListener('keyup',()=>document.querySelectorAll('.nd-pressed').forEach(x=>x.classList.remove('nd-pressed')),true);
const mo=new MutationObserver(ms=>{for(const m of ms){const el=m.target.nodeType===3?m.target.parentElement:m.target;if(el?.matches?.('.hud strong,.box strong,#score'))pop(el)}});if(document.body)mo.observe(document.body,{subtree:true,childList:true,characterData:true});
})();