(()=>{'use strict';
const C=document.getElementById('game'),c=C.getContext('2d'),$=id=>document.getElementById(id);
const COLORS=['#ff6078','#58dfff','#64e39b','#ffd45f'],CFG={rookie:{bpm:82,speed:170,window:55,time:42},pro:{bpm:108,speed:210,window:43,time:38},hard:{bpm:136,speed:255,window:33,time:35},legend:{bpm:164,speed:305,window:25,time:32}};
let diff=localStorage.nd_beat_diff||'pro',play=false,score=0,stage=1,combo=0,best=+(localStorage.nd_beat||0),left=38,notes=[],spawn=0,lastLane=-1,hits=0,misses=0,fx=[],laneFlash=[0,0,0,0],msg='',msgT=0;
function cfg(){return CFG[diff]}function setDiff(d){if(!CFG[d])return;diff=d;localStorage.nd_beat_diff=d;document.querySelectorAll('[data-diff]').forEach(b=>b.classList.toggle('active',b.dataset.diff===d));hud()}
function toast(t){msg=t;msgT=.55;$('toast').textContent=t;$('toast').classList.add('show')}
function hud(){const acc=hits+misses?Math.round(hits/(hits+misses)*100):100;$('score').textContent=score;$('round').textContent=stage;$('streak').textContent=combo;$('best').textContent=best;$('status').textContent='TIME '+Math.max(0,left).toFixed(1)+' · ACC '+acc+'% · '+cfg().bpm+' BPM';$('progressFill').style.width=((cfg().time-left)/cfg().time*100)+'%';if(score>best){best=score;localStorage.nd_beat=best;$('best').textContent=best}}
function reset(){play=true;score=combo=hits=misses=0;stage=1;left=cfg().time;notes=[];fx=[];laneFlash=[0,0,0,0];spawn=.25;lastLane=-1;$('overlay').classList.add('hide');hud()}
function finish(){play=false;const acc=hits+misses?Math.round(hits/(hits+misses)*100):100;$('title').textContent='TRACK COMPLETE';$('msg').textContent='Score '+score+' · Accuracy '+acc+'% · Best '+best;$('start').textContent='PLAY AGAIN';$('overlay').classList.remove('hide')}
function spawnNote(){let lane=Math.floor(Math.random()*4);if(lane===lastLane&&Math.random()<.75)lane=(lane+1+Math.floor(Math.random()*3))%4;lastLane=lane;notes.push({lane,y:-36,hit:false});spawn=60/cfg().bpm*(.92+Math.random()*.16)}
function tap(lane){if(!play)return;laneFlash[lane]=.12;let bn=null,bd=1e9;for(const n of notes)if(!n.hit&&n.lane===lane){const d=Math.abs(n.y-500);if(d<bd){bd=d;bn=n}}if(bn&&bd<=cfg().window){bn.hit=true;hits++;let judge='GOOD',pts=80;if(bd<=cfg().window*.28){judge='PERFECT';pts=160}else if(bd<=cfg().window*.62){judge='GREAT';pts=115}score+=pts+combo*9;combo++;fx.push({lane,t:.3});if(judge==='PERFECT')window.NDPolish?.flash();toast(judge+(combo>=5?' · x'+combo:''))}else{misses++;combo=0;score=Math.max(0,score-15);window.NDPolish?.shake();toast('MISS')}hud()}
function update(dt){if(msgT>0){msgT-=dt;if(msgT<=0){msg='';$('toast').classList.remove('show')}}laneFlash=laneFlash.map(v=>Math.max(0,v-dt));for(const f of fx)f.t-=dt;fx=fx.filter(f=>f.t>0);if(!play)return;left-=dt;if(left<=0){finish();return}stage=1+Math.floor((cfg().time-left)/8);spawn-=dt;if(spawn<=0)spawnNote();const speed=cfg().speed*(1+(stage-1)*.04);for(const n of notes)n.y+=speed*dt;for(const n of notes)if(!n.hit&&n.y>500+cfg().window){n.hit=true;misses++;combo=0;window.NDPolish?.shake();toast('MISS')}notes=notes.filter(n=>n.y<620&&!n.hit);hud()}
function draw(){c.fillStyle='#050a13';c.fillRect(0,0,640,600);for(let i=0;i<4;i++){const x=78+i*122;c.fillStyle=laneFlash[i]?COLORS[i]+'33':i%2?'#0d1724':'#101b29';c.fillRect(x,0,112,600);c.strokeStyle='#24384d';c.strokeRect(x,0,112,600);c.fillStyle=COLORS[i]+'20';c.fillRect(x,0,112,10)}c.fillStyle='#ffffff18';c.fillRect(68,488,504,24);c.fillStyle='#fff';c.fillRect(68,499,504,4);for(const n of notes){const x=97+n.lane*122;c.shadowColor=COLORS[n.lane];c.shadowBlur=16;c.fillStyle=COLORS[n.lane];c.fillRect(x,n.y,74,28);c.shadowBlur=0;c.fillStyle='#ffffff66';c.fillRect(x+8,n.y+5,58,5)}for(const f of fx){const a=f.t/.3,x=134+f.lane*122;c.globalAlpha=a;c.strokeStyle=COLORS[f.lane];c.lineWidth=6;c.beginPath();c.arc(x,500,(1-a)*50+14,0,Math.PI*2);c.stroke()}c.globalAlpha=1;c.fillStyle='#9db2c6';c.font='900 13px system-ui';c.textAlign='center';c.fillText('D / F / J / K · HIT EXACTLY ON THE WHITE LINE',320,32)}
document.querySelectorAll('[data-lane]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();tap(+b.dataset.lane)}});$('start').onclick=$('restart').onclick=reset;document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{if(!play)setDiff(b.dataset.diff)});addEventListener('keydown',e=>{const map={d:0,f:1,j:2,k:3,'1':0,'2':1,'3':2,'4':3},k=e.key.toLowerCase();if(k in map&&!e.repeat){e.preventDefault();tap(map[k])}});let last=0;function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}setDiff(diff);hud();requestAnimationFrame(loop)})();