(()=>{'use strict';
const C=document.getElementById('game'),c=C.getContext('2d'),$=id=>document.getElementById(id);
const COLORS=['#ff6078','#58dfff','#64e39b','#ffd45f'],CFG={rookie:{bpm:88,speed:170,window:54,time:42},pro:{bpm:112,speed:210,window:42,time:38},hard:{bpm:138,speed:255,window:32,time:35},legend:{bpm:166,speed:305,window:25,time:32}};
let diff=localStorage.nd_beat_diff||'pro',playing=false,score=0,level=1,combo=0,best=+(localStorage.nd_beat||0),left=38,notes=[],spawn=0,lastLane=-1,sparks=[],toastT=0,hits=0,misses=0;
function cfg(){return CFG[diff]}function setDiff(d){if(!CFG[d])return;diff=d;localStorage.nd_beat_diff=d;document.querySelectorAll('[data-diff]').forEach(b=>b.classList.toggle('active',b.dataset.diff===d));hud()}
function beep(freq){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;window._ndBeatAC=window._ndBeatAC||new A();const ac=window._ndBeatAC,o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;g.gain.value=.025;o.connect(g);g.connect(ac.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+.06);o.stop(ac.currentTime+.07)}catch(e){}}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');toastT=.5}
function hud(){const acc=hits+misses?Math.round(hits/(hits+misses)*100):100;$('score').textContent=score;$('round').textContent=level;$('streak').textContent=combo;$('best').textContent=best;$('status').textContent='TIME '+Math.max(0,left).toFixed(1)+' · ACC '+acc+'% · '+cfg().bpm+' BPM';if(score>best){best=score;localStorage.nd_beat=best;$('best').textContent=best}$('progressFill').style.width=((cfg().time-left)/cfg().time*100)+'%'}
function reset(){playing=true;score=combo=hits=misses=0;level=1;left=cfg().time;notes=[];sparks=[];spawn=.3;lastLane=-1;$('overlay').classList.add('hide');hud()}
function end(){playing=false;if(score>best){best=score;localStorage.nd_beat=best}$('title').textContent='TRACK COMPLETE';$('msg').textContent='Score '+score+' · Best '+best+' · Accuracy '+(hits+misses?Math.round(hits/(hits+misses)*100):100)+'%';$('start').textContent='PLAY AGAIN';$('overlay').classList.remove('hide')}
function spawnNote(){let lane=Math.floor(Math.random()*4);if(lane===lastLane&&Math.random()<.72)lane=(lane+1+Math.floor(Math.random()*3))%4;lastLane=lane;notes.push({lane,y:-40,hit:false});spawn=60/cfg().bpm*(.88+Math.random()*.24)}
function tapLane(lane){if(!playing)return;let bestN=null,bd=1e9;for(const n of notes){if(!n.hit&&n.lane===lane){const d=Math.abs(n.y-500);if(d<bd){bd=d;bestN=n}}}if(bestN&&bd<=cfg().window){bestN.hit=true;hits++;let judge='GOOD',pts=80;if(bd<=cfg().window*.28){judge='PERFECT';pts=150;beep(760)}else if(bd<=cfg().window*.62){judge='GREAT';pts=110;beep(620)}else beep(520);score+=pts+combo*8;combo++;toast(judge);sparks.push({lane,t:.28})}else{misses++;combo=0;score=Math.max(0,score-20);toast('MISS') }hud()}
function update(dt){if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}if(!playing)return;left-=dt;if(left<=0){end();return}level=1+Math.floor((cfg().time-left)/9);spawn-=dt;if(spawn<=0)spawnNote();const speed=cfg().speed*(1+(level-1)*.035);for(const n of notes)n.y+=speed*dt;for(const n of notes){if(!n.hit&&n.y>500+cfg().window){n.hit=true;misses++;combo=0;toast('MISS')}}notes=notes.filter(n=>n.y<620&&!n.hit);for(const s of sparks)s.t-=dt;sparks=sparks.filter(s=>s.t>0);hud()}
function draw(){c.fillStyle='#060a13';c.fillRect(0,0,640,600);for(let i=0;i<4;i++){const x=78+i*122;c.fillStyle=i%2?'#0d1724':'#101b29';c.fillRect(x,0,112,600);c.strokeStyle='#24384d';c.strokeRect(x,0,112,600)}c.fillStyle='#ffffff18';c.fillRect(68,490,504,20);c.fillStyle='#ffffffb8';c.fillRect(68,498,504,4);for(const n of notes){const x=97+n.lane*122;c.shadowColor=COLORS[n.lane];c.shadowBlur=15;c.fillStyle=COLORS[n.lane];c.fillRect(x,n.y,74,28);c.shadowBlur=0;c.fillStyle='#ffffff55';c.fillRect(x+8,n.y+5,58,5)}for(const s of sparks){const x=134+s.lane*122,a=s.t/.28;c.globalAlpha=a;c.strokeStyle=COLORS[s.lane];c.lineWidth=5;c.beginPath();c.arc(x,500,(1-a)*45+15,0,Math.PI*2);c.stroke();c.globalAlpha=1}c.fillStyle='#9db2c6';c.font='900 13px system-ui';c.textAlign='center';c.fillText('D / F / J / K · HIT ON THE WHITE LINE',320,32)}
document.querySelectorAll('[data-lane]').forEach(b=>b.onclick=()=>tapLane(+b.dataset.lane));$('start').onclick=$('restart').onclick=reset;
document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{if(!playing)setDiff(b.dataset.diff)});
addEventListener('keydown',e=>{const map={d:0,f:1,j:2,k:3,'1':0,'2':1,'3':2,'4':3};const k=e.key.toLowerCase();if(k in map&&!e.repeat){e.preventDefault();tapLane(map[k])}});
let last=0;function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}setDiff(diff);hud();requestAnimationFrame(loop);
})();