(()=>{'use strict';
const C=document.getElementById('game'),c=C.getContext('2d'),$=id=>document.getElementById(id);
const CFG={rookie:{meter:.68,tol:.17,jitter:.012},pro:{meter:.92,tol:.13,jitter:.022},hard:{meter:1.18,tol:.095,jitter:.038},legend:{meter:1.45,tol:.07,jitter:.052}};
const PINS=[[320,90],[292,120],[348,120],[264,150],[320,150],[376,150],[236,182],[292,182],[348,182],[404,182]];
let diff=localStorage.nd_bowling_diff||'pro',play=false,score=0,frame=1,roll=1,streak=0,best=+(localStorage.nd_bowling||0),aim=.5,spin=0,power=.2,pdir=1,phase='aim',alive=Array(10).fill(true),ball=null,fallen=[],msg='',msgT=0;
function cfg(){return CFG[diff]}function setDiff(d){if(!CFG[d])return;diff=d;localStorage.nd_bowling_diff=d;document.querySelectorAll('[data-diff]').forEach(b=>b.classList.toggle('active',b.dataset.diff===d));hud()}
function toast(t){msg=t;msgT=.9;$('toast').textContent=t;$('toast').classList.add('show')}
function hud(){$('score').textContent=score;$('round').textContent=Math.min(frame,10)+'/10';$('streak').textContent=streak;$('best').textContent=best;$('status').textContent=phase==='aim'?'STEP 1 · SET LINE':phase==='power'?'STEP 2 · SPIN '+spin.toFixed(1)+' · POWER '+Math.round(power*100)+'%':'ROLLING';$('progressFill').style.width=((Math.min(frame-1,10)+(roll-1)/2)/10*100)+'%';if(score>best){best=score;localStorage.nd_bowling=best;$('best').textContent=best}}
function resetPins(){alive=Array(10).fill(true);fallen=[]}
function reset(){play=true;score=0;frame=1;roll=1;streak=0;aim=.5;spin=0;power=.2;pdir=1;phase='aim';ball=null;resetPins();$('overlay').classList.add('hide');hud()}
function finish(){play=false;$('title').textContent='TEN FRAMES COMPLETE';$('msg').textContent='Score '+score+' · Best '+best;$('start').textContent='BOWL AGAIN';$('overlay').classList.remove('hide')}
function move(d){if(!play||phase==='roll')return;if(phase==='aim')aim=Math.max(.1,Math.min(.9,aim+d*.045));else spin=Math.max(-1,Math.min(1,spin+d*.12));hud()}
function action(){if(!play||phase==='roll')return;if(phase==='aim'){phase='power';toast('LINE LOCKED');hud();return}launch()}
function launch(){const q=cfg(),pocket=.515,err=Math.abs((aim+spin*.055)-pocket+(Math.random()-.5)*q.jitter),pErr=Math.abs(power-.76),quality=Math.max(0,1-err/(q.tol*2.1)-pErr/.42);ball={t:0,d:.9,sx:140+aim*360,ex:320+(aim-.5)*95+spin*48,q:quality};phase='roll';hud()}
function resolve(){const remain=alive.reduce((a,b)=>a+(b?1:0),0),q=ball.q;let knock=Math.round(remain*Math.max(.05,Math.min(1,.14+q*.92+(Math.random()-.5)*.1)));if(q>.9&&roll===1)knock=remain;if(q>.75&&remain<=3)knock=remain;const ids=alive.map((v,i)=>v?i:-1).filter(i=>i>=0).sort(()=>Math.random()-.5);fallen=[];for(let i=0;i<Math.min(knock,ids.length);i++){alive[ids[i]]=false;fallen.push({i:ids[i],t:.8,rot:(Math.random()-.5)*1.4})}const left=alive.reduce((a,b)=>a+(b?1:0),0);score+=knock*10;if(left===0&&roll===1){score+=100+streak*25;streak++;toast('🎳 STRIKE');nextFrame()}else if(left===0){score+=50;streak++;toast('✨ SPARE');nextFrame()}else if(roll===1){roll=2;streak=0;phase='aim';aim=.5;spin=0;power=.2;toast(knock+' PINS')}else{streak=0;toast(knock+' PINS');nextFrame()}ball=null;hud()}
function nextFrame(){frame++;roll=1;aim=.5;spin=0;power=.2;phase='aim';resetPins();if(frame>10){finish()}}
function update(dt){if(msgT>0){msgT-=dt;if(msgT<=0){msg='';$('toast').classList.remove('show')}}for(const f of fallen)f.t-=dt;fallen=fallen.filter(f=>f.t>0);if(!play)return;if(phase==='power'){power+=pdir*cfg().meter*dt;if(power>=1){power=1;pdir=-1}else if(power<=0){power=0;pdir=1}}if(ball){ball.t+=dt;if(ball.t>=ball.d)resolve()}hud()}
function lane(){const g=c.createLinearGradient(0,0,0,600);g.addColorStop(0,'#4d301e');g.addColorStop(1,'#c79761');c.fillStyle='#071019';c.fillRect(0,0,640,600);c.fillStyle=g;c.beginPath();c.moveTo(215,0);c.lineTo(425,0);c.lineTo(585,600);c.lineTo(55,600);c.closePath();c.fill();c.strokeStyle='#ffffff12';for(let y=60;y<600;y+=70){c.beginPath();c.moveTo(100,y);c.lineTo(540,y);c.stroke()}}
function draw(){lane();alive.forEach((v,i)=>{if(!v)return;const [x,y]=PINS[i];c.fillStyle='#fff';c.beginPath();c.ellipse(x,y,10,18,0,0,Math.PI*2);c.fill();c.fillStyle='#ff6078';c.fillRect(x-8,y-3,16,4)});for(const f of fallen){const [x,y]=PINS[f.i];c.save();c.translate(x,y);c.rotate(f.rot*(1-f.t/.8));c.globalAlpha=Math.max(0,f.t/.8);c.fillStyle='#fff';c.fillRect(-5,-17,10,34);c.restore()}c.globalAlpha=1;
let bx=140+aim*360,by=510,s=1;if(ball){const p=Math.min(1,ball.t/ball.d),e=1-Math.pow(1-p,2);bx=ball.sx+(ball.ex-ball.sx)*e;by=510+(198-510)*e;s=1-.58*e}c.fillStyle='#58dfff';c.beginPath();c.arc(bx,by,24*s,0,Math.PI*2);c.fill();c.fillStyle='#0b1721';c.beginPath();c.arc(bx-7*s,by-4*s,3*s,0,Math.PI*2);c.arc(bx+4*s,by-9*s,3*s,0,Math.PI*2);c.fill();
if(phase!=='roll'){c.strokeStyle='#64e39b';c.lineWidth=4;c.beginPath();c.moveTo(140+aim*360,475);c.lineTo(320+(aim-.5)*100+spin*50,205);c.stroke()}c.fillStyle='#08131d';c.fillRect(105,548,430,22);c.fillStyle='#64e39b';c.fillRect(105+(.76-.1)*430,548,.2*430,22);c.fillStyle='#fff';c.fillRect(105+power*430-4,540,8,38);c.fillStyle='#f7fbff';c.font='900 12px system-ui';c.textAlign='center';c.fillText('FRAME '+Math.min(frame,10)+' · ROLL '+roll+' · '+(alive.filter(Boolean).length)+' PINS LEFT',320,34)}
$('left').onpointerdown=()=>move(-1);$('right').onpointerdown=()=>move(1);$('action').onclick=action;$('start').onclick=$('restart').onclick=reset;document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{if(!play)setDiff(b.dataset.diff)});addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a'){e.preventDefault();move(-1)}if(k==='arrowright'||k==='d'){e.preventDefault();move(1)}if(e.code==='Space'){e.preventDefault();action()}});let last=0;function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}setDiff(diff);hud();requestAnimationFrame(loop)})();