(()=>{'use strict';
const C=document.getElementById('game'),c=C.getContext('2d'),$=id=>document.getElementById(id);
const CFG={rookie:{meter:.72,tol:.18,jitter:.010,pSweet:.15,curve:.85},pro:{meter:.95,tol:.135,jitter:.020,pSweet:.11,curve:1},hard:{meter:1.18,tol:.10,jitter:.034,pSweet:.082,curve:1.12},legend:{meter:1.42,tol:.075,jitter:.048,pSweet:.060,curve:1.24}};
const PIN_LAYOUT=[[0,0],[-1,1],[1,1],[-2,2],[0,2],[2,2],[-3,3],[-1,3],[1,3],[3,3]];
let diff=localStorage.nd_bowling_diff||'pro',play=false,score=0,frame=1,roll=1,streak=0,best=+(localStorage.nd_bowling||0);
let aim=.5,spin=0,power=.25,pdir=1,powerTarget=.72,phase='aim',pins=[],fallen=[],ball=null,msg='',msgT=0,camShake=0,flash=0;
function cfg(){return CFG[diff]}
function setDiff(d){if(!CFG[d])return;diff=d;localStorage.nd_bowling_diff=d;document.querySelectorAll('[data-diff]').forEach(b=>b.classList.toggle('active',b.dataset.diff===d));hud()}
function toast(t){msg=t;msgT=.9;$('toast').textContent=t;$('toast').classList.add('show')}
function shake(n=.22){camShake=Math.max(camShake,n);window.NDPolish?.shake()}
function flashHit(n=.14){flash=Math.max(flash,n);window.NDPolish?.flash()}
function hud(){$('score').textContent=score;$('round').textContent=Math.min(frame,10)+'/10';$('streak').textContent=streak;$('best').textContent=best;$('status').textContent=phase==='aim'?'STEP 1 · AIM':phase==='power'?'STEP 2 · SPIN '+spin.toFixed(1)+' · POWER '+Math.round(power*100)+'%':'BALL ROLLING';$('progressFill').style.width=((Math.min(frame-1,10)+(roll-1)/2)/10*100)+'%';if(score>best){best=score;localStorage.nd_bowling=best;$('best').textContent=best}}
function newPowerTarget(){const q=cfg();powerTarget=.44+Math.random()*.44;power=Math.max(.08,Math.min(.92,powerTarget+(Math.random()-.5)*.34));pdir=Math.random()<.5?-1:1;return q}
function resetPins(){pins=PIN_LAYOUT.map((p,i)=>({id:i,alive:true,ox:p[0],oy:p[1],fall:0,rot:0,driftX:0,driftY:0}));fallen=[]}
function reset(){play=true;score=0;frame=1;roll=1;streak=0;aim=.5;spin=0;phase='aim';ball=null;msg='';camShake=0;flash=0;resetPins();newPowerTarget();$('overlay').classList.add('hide');hud()}
function finish(){play=false;$('title').textContent='TEN FRAMES COMPLETE';$('msg').textContent='Score '+score+' · Best '+best;$('start').textContent='BOWL AGAIN';$('overlay').classList.remove('hide')}
function move(d){if(!play||phase==='roll')return;if(phase==='aim')aim=Math.max(.08,Math.min(.92,aim+d*.045));else spin=Math.max(-1,Math.min(1,spin+d*.12));hud()}
function action(){if(!play||phase==='roll')return;if(phase==='aim'){phase='power';toast('LINE LOCKED');hud();return}launch()}
function launch(){const q=cfg(),pocket=.515,line=aim+spin*.055,err=Math.abs(line-pocket+(Math.random()-.5)*q.jitter),pErr=Math.abs(power-powerTarget),quality=Math.max(0,1-err/(q.tol*2.1)-pErr/(q.pSweet*2.25));ball={t:0,d:.92,sx:aim,ex:.5+(aim-.5)*.18+spin*.09,curve:spin*.11*q.curve,q:quality};phase='roll';hud()}
function resolveRoll(){const remain=pins.filter(p=>p.alive),q=ball.q;let knock=Math.round(remain.length*Math.max(.05,Math.min(1,.16+q*.9+(Math.random()-.5)*.1)));if(q>.92&&roll===1)knock=remain.length;if(q>.78&&remain.length<=3)knock=remain.length;remain.sort(()=>Math.random()-.5);const take=remain.slice(0,Math.min(knock,remain.length));fallen=[];for(const p of take){p.alive=false;p.fall=.85;p.rot=(Math.random()-.5)*1.9;p.driftX=(Math.random()-.5)*34;p.driftY=12+Math.random()*26;fallen.push(p)}const left=pins.filter(p=>p.alive).length;score+=knock*10;if(left===0&&roll===1){score+=100+streak*25;streak++;flashHit(.18);toast('🎳 STRIKE');nextFrame()}else if(left===0){score+=50;streak++;flashHit(.16);toast('✨ SPARE');nextFrame()}else if(roll===1){roll=2;streak=0;phase='aim';aim=.5;spin=0;newPowerTarget();shake(.16);toast(knock+' PINS')}else{streak=0;shake(.12);toast(knock+' PINS');nextFrame()}ball=null;hud()}
function nextFrame(){frame++;roll=1;aim=.5;spin=0;phase='aim';resetPins();newPowerTarget();if(frame>10)finish()}
function lanePoint(nx,ny){const topY=78,botY=555,y=topY+(botY-topY)*ny,leftTop=245,rightTop=395,leftBot=72,rightBot=568,left=leftTop+(leftBot-leftTop)*ny,right=rightTop+(rightBot-rightTop)*ny;return{x:left+(right-left)*nx,y,left,right,width:right-left}}
function pinScreen(pin){const depth=.085+pin.oy*.07,nx=.5+pin.ox*.065,p=lanePoint(nx,depth),scale=.45+depth*1.12;return{...p,scale,depth}}
function update(dt){if(msgT>0){msgT-=dt;if(msgT<=0){msg='';$('toast').classList.remove('show')}}camShake=Math.max(0,camShake-dt*1.8);flash=Math.max(0,flash-dt*1.6);for(const p of fallen)p.fall-=dt;if(!play)return;if(phase==='power'){power+=pdir*cfg().meter*dt;if(power>=1){power=1;pdir=-1}else if(power<=0){power=0;pdir=1}}if(ball){ball.t+=dt;if(ball.t>=ball.d)resolveRoll()}hud()}
function drawLane(){const g=c.createLinearGradient(0,0,0,600);g.addColorStop(0,'#1a202c');g.addColorStop(.2,'#6b4628');g.addColorStop(.55,'#c08a55');g.addColorStop(1,'#82532f');c.fillStyle='#071019';c.fillRect(0,0,640,600);c.fillStyle='#111b28';c.fillRect(0,0,640,600);c.beginPath();c.moveTo(245,78);c.lineTo(395,78);c.lineTo(568,555);c.lineTo(72,555);c.closePath();c.fillStyle=g;c.fill();c.strokeStyle='#ffffff12';c.lineWidth=1.5;for(let i=1;i<=8;i++){const y=i/9,a=lanePoint(0,y),b=lanePoint(1,y);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()}for(let i=1;i<=4;i++){const x=i/5,a=lanePoint(x,0),b=lanePoint(x,1);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()}c.strokeStyle='#d7b184';c.lineWidth=3;c.beginPath();c.moveTo(245,78);c.lineTo(72,555);c.moveTo(395,78);c.lineTo(568,555);c.stroke();c.fillStyle='#182737';c.fillRect(0,0,640,72)}
function drawPins(){const all=pins.slice().sort((a,b)=>pinScreen(a).depth-pinScreen(b).depth);for(const p of all){if(!p.alive&&p.fall<=0)continue;const s=pinScreen(p);let x=s.x,y=s.y,rot=0,alpha=1;if(!p.alive){const t=1-Math.max(0,p.fall)/.85;x+=p.driftX*t;y+=p.driftY*t;rot=p.rot*t;alpha=1-t*.15}c.save();c.translate(x,y);c.rotate(rot);c.globalAlpha=alpha;const w=12*s.scale,h=24*s.scale;c.fillStyle='#fff';c.beginPath();c.ellipse(0,0,w*.72,h,0,0,Math.PI*2);c.fill();c.fillStyle='#ff6078';c.fillRect(-w*.62,-h*.12,w*1.24,h*.18);c.fillStyle='#d9e4ef';c.fillRect(-w*.35,-h*.78,w*.7,h*.18);c.restore()}c.globalAlpha=1}
function drawBall(){let nx=aim,ny=1,curve=spin*.1,scale=1;if(ball){const t=Math.min(1,ball.t/ball.d),e=1-Math.pow(1-t,2);ny=e;nx=ball.sx+(ball.ex-ball.sx)*e+Math.sin(e*Math.PI)*ball.curve;curve=ball.curve;scale=1-.58*e}const p=lanePoint(nx,ny*.92),r=26*scale*(.78+ny*.25);c.save();c.translate(p.x,p.y);c.fillStyle='#58dfff';c.beginPath();c.arc(0,0,r,0,Math.PI*2);c.fill();c.fillStyle='#0b1721';c.beginPath();c.arc(-r*.35,-r*.15,r*.14,0,Math.PI*2);c.arc(r*.18,-r*.36,r*.14,0,Math.PI*2);c.arc(-r*.03,r*.05,r*.12,0,Math.PI*2);c.fill();c.restore();if(phase!=='roll'){const a=lanePoint(aim,.92),b=lanePoint(.5+(aim-.5)*.18+spin*.09,.19);c.strokeStyle='#64e39b';c.lineWidth=4;c.beginPath();c.moveTo(a.x,a.y);c.quadraticCurveTo((a.x+b.x)/2+curve*80,(a.y+b.y)/2,b.x,b.y);c.stroke()}}
function drawMeter(){c.fillStyle='#08131d';c.fillRect(105,548,430,22);const sw=cfg().pSweet,zoneX=105+(powerTarget-sw)*430,zoneW=sw*2*430;c.fillStyle='#64e39b';c.fillRect(zoneX,548,zoneW,22);c.strokeStyle='#b8ffd7';c.lineWidth=2;c.strokeRect(zoneX,548,zoneW,22);c.fillStyle='#fff';c.fillRect(105+power*430-4,540,8,38)}
function drawHudText(){c.fillStyle='#f7fbff';c.font='900 12px system-ui';c.textAlign='center';c.fillText('FRAME '+Math.min(frame,10)+' · ROLL '+roll+' · '+pins.filter(p=>p.alive).length+' PINS LEFT',320,30);c.fillStyle='#c8d5e2';c.fillText(phase==='aim'?'MOVE TO AIM · PRESS ACTION TO LOCK':phase==='power'?'STOP THE POWER BAR IN THE GREEN':'WATCH THE ROLL',320,48)}
function drawFlash(){if(flash<=0)return;c.save();c.globalAlpha=flash*.42;c.fillStyle='#fff';c.fillRect(0,0,640,600);c.restore()}
function draw(){c.clearRect(0,0,640,600);const sx=(Math.random()-.5)*camShake*18,sy=(Math.random()-.5)*camShake*12;c.save();c.translate(sx,sy);drawLane();drawPins();drawBall();drawMeter();drawHudText();c.restore();drawFlash()}
$('left').onpointerdown=()=>move(-1);$('right').onpointerdown=()=>move(1);$('action').onclick=action;$('start').onclick=$('restart').onclick=reset;document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{if(!play)setDiff(b.dataset.diff)});addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a'){e.preventDefault();move(-1)}if(k==='arrowright'||k==='d'){e.preventDefault();move(1)}if(e.code==='Space'){e.preventDefault();action()}});let last=0;function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}setDiff(diff);resetPins();newPowerTarget();hud();requestAnimationFrame(loop)})();