(()=>{'use strict';
const C=document.getElementById('game'),c=C.getContext('2d'),$=id=>document.getElementById(id);
const CFG={rookie:{start:3,flash:.68,lives:4},pro:{start:4,flash:.52,lives:3},hard:{start:5,flash:.4,lives:3},legend:{start:6,flash:.31,lives:2}};
const COLORS=['#ff6078','#58dfff','#64e39b','#ffd45f','#9c7cff','#ff955c','#5ce5dc','#ef72d2','#b7e85b'];
let diff=localStorage.nd_circuit_diff||'pro',playing=false,score=0,level=1,streak=0,best=+(localStorage.nd_circuit||0),lives=3,seq=[],input=0,phase='ready',showIndex=0,lit=false,timer=0,pressed=-1,pressedT=0,toastT=0,wait=0;
function cfg(){return CFG[diff]}function setDiff(d){if(!CFG[d])return;diff=d;localStorage.nd_circuit_diff=d;document.querySelectorAll('[data-diff]').forEach(b=>b.classList.toggle('active',b.dataset.diff===d));hud()}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');toastT=.75}
function hud(){$('score').textContent=score;$('round').textContent=level;$('streak').textContent=streak;$('best').textContent=best;$('status').textContent='LIVES '+lives+' · '+(phase==='show'?'WATCH':phase==='input'?'REPEAT '+input+'/'+seq.length:phase==='clear'?'LEVEL CLEARED':'READY');if(score>best){best=score;localStorage.nd_circuit=best;$('best').textContent=best}$('progressFill').style.width=(phase==='input'?input/seq.length*100:phase==='clear'?100:0)+'%'}
function addNode(){let n=Math.floor(Math.random()*9);if(seq.length>1&&n===seq[seq.length-1])n=(n+1+Math.floor(Math.random()*8))%9;seq.push(n)}
function beginShow(){phase='show';showIndex=0;lit=false;timer=.22;input=0;hud()}
function reset(){playing=true;score=0;level=1;streak=0;lives=cfg().lives;seq=[];for(let i=0;i<cfg().start;i++)addNode();pressed=-1;wait=0;$('overlay').classList.add('hide');beginShow()}
function end(){playing=false;phase='over';if(score>best){best=score;localStorage.nd_circuit=best}$('title').textContent='SYSTEM LOCKED';$('msg').textContent='Score '+score+' · Best '+best+' · Level '+level;$('start').textContent='HACK AGAIN';$('overlay').classList.remove('hide');hud()}
function tap(i){if(!playing||phase!=='input')return;pressed=i;pressedT=.12;if(seq[input]===i){score+=90+level*20+streak*7;streak++;input++;if(input>=seq.length){score+=180+level*35;level++;addNode();phase='clear';wait=.65;toast('NODE CHAIN CLEARED')}}else{lives--;streak=0;toast('WRONG NODE');phase='retry';wait=.75;if(lives<=0){end();return}}hud()}
function update(dt){if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}pressedT=Math.max(0,pressedT-dt);if(pressedT<=0)pressed=-1;if(!playing)return;if(phase==='clear'||phase==='retry'){wait-=dt;if(wait<=0)beginShow();return}if(phase!=='show')return;timer-=dt;if(timer<=0){if(!lit){lit=true;timer=cfg().flash*.62}else{lit=false;showIndex++;if(showIndex>=seq.length){phase='input';showIndex=0;hud()}else timer=cfg().flash*.3}}}
function nodeXY(i){return{x:160+(i%3)*160,y:150+Math.floor(i/3)*150}}
function draw(){c.fillStyle='#060b14';c.fillRect(0,0,640,600);c.strokeStyle='#15354d';c.lineWidth=2;for(let x=0;x<640;x+=40){c.beginPath();c.moveTo(x,0);c.lineTo(x,600);c.stroke()}for(let y=0;y<600;y+=40){c.beginPath();c.moveTo(0,y);c.lineTo(640,y);c.stroke()}c.strokeStyle='#2b5570';c.lineWidth=3;for(let i=0;i<9;i++){const a=nodeXY(i);for(const j of [i+1,i+3])if(j<9&&((j===i+1&&i%3<2)||j===i+3)){const b=nodeXY(j);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()}}if(phase==='show'&&lit&&seq.length){const upto=Math.min(showIndex,seq.length-1);c.strokeStyle='#58dfff';c.lineWidth=6;c.shadowColor='#58dfff';c.shadowBlur=12;for(let k=1;k<=upto;k++){const a=nodeXY(seq[k-1]),b=nodeXY(seq[k]);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()}c.shadowBlur=0}
for(let i=0;i<9;i++){const p=nodeXY(i),active=(phase==='show'&&lit&&seq[showIndex]===i)||pressed===i;c.shadowColor=COLORS[i];c.shadowBlur=active?28:6;c.fillStyle=active?COLORS[i]:'#162434';c.beginPath();c.arc(p.x,p.y,46,0,Math.PI*2);c.fill();c.shadowBlur=0;c.strokeStyle=active?'#fff':'#355069';c.lineWidth=active?5:3;c.stroke();c.fillStyle=active?'#071018':'#9bb0c4';c.font='1000 22px system-ui';c.textAlign='center';c.fillText(String(i+1),p.x,p.y+7)}
c.fillStyle='#9fb4c9';c.font='900 13px system-ui';c.textAlign='center';c.fillText(phase==='show'?'WATCH THE PULSE PATH':phase==='input'?'REPEAT THE SEQUENCE':'CIRCUIT HACKER',320,45)}
C.addEventListener('pointerdown',e=>{e.preventDefault();const r=C.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*640,y=(e.clientY-r.top)/r.height*600;let bi=-1,bd=1e9;for(let i=0;i<9;i++){const p=nodeXY(i),d=(p.x-x)**2+(p.y-y)**2;if(d<bd){bd=d;bi=i}}if(bd<70*70)tap(bi)});
addEventListener('keydown',e=>{const n=Number(e.key);if(n>=1&&n<=9)tap(n-1)});
$('start').onclick=$('restart').onclick=reset;document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{if(!playing)setDiff(b.dataset.diff)});
let last=0;function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}setDiff(diff);hud();requestAnimationFrame(loop);
})();