(()=>{'use strict';
const C=document.getElementById('game'),c=C.getContext('2d'),$=id=>document.getElementById(id);
const CFG={rookie:{start:3,on:.62,gap:.26,lives:4},pro:{start:4,on:.48,gap:.2,lives:3},hard:{start:5,on:.36,gap:.16,lives:3},legend:{start:6,on:.28,gap:.12,lives:2}};
const COLORS=['#ff6078','#58dfff','#64e39b','#ffd45f','#9c7cff','#ff955c','#5ce5dc','#ef72d2','#b7e85b'];
let diff=localStorage.nd_circuit_diff||'pro',play=false,score=0,level=1,streak=0,best=+(localStorage.nd_circuit||0),lives=3,seq=[],input=0,phase='ready',idx=0,lit=false,timer=0,pressed=-1,pressT=0,trail=[],msg='',msgT=0;
const pos=i=>({x:160+(i%3)*160,y:150+Math.floor(i/3)*150});
function cfg(){return CFG[diff]}function setDiff(d){if(!CFG[d])return;diff=d;localStorage.nd_circuit_diff=d;document.querySelectorAll('[data-diff]').forEach(b=>b.classList.toggle('active',b.dataset.diff===d));hud()}
function toast(t){msg=t;msgT=.8;$('toast').textContent=t;$('toast').classList.add('show')}
function hud(){$('score').textContent=score;$('round').textContent=level;$('streak').textContent=streak;$('best').textContent=best;$('status').textContent='LIVES '+lives+' · '+(phase==='show'?'WATCH THE PATH':phase==='input'?'YOUR TURN '+input+'/'+seq.length:phase==='clear'?'LEVEL CLEARED':'READY');$('progressFill').style.width=(phase==='input'?input/seq.length*100:phase==='clear'?100:0)+'%';if(score>best){best=score;localStorage.nd_circuit=best;$('best').textContent=best}}
function addNode(){let n=Math.floor(Math.random()*9);if(seq.length&&n===seq[seq.length-1])n=(n+1+Math.floor(Math.random()*8))%9;seq.push(n)}
function show(){phase='show';idx=0;lit=false;timer=.3;input=0;trail=[];hud()}
function reset(){play=true;score=streak=0;level=1;lives=cfg().lives;seq=[];for(let i=0;i<cfg().start;i++)addNode();pressed=-1;$('overlay').classList.add('hide');show()}
function end(){play=false;$('title').textContent='SYSTEM LOCKED';$('msg').textContent='Score '+score+' · Best '+best+' · Reached level '+level;$('start').textContent='HACK AGAIN';$('overlay').classList.remove('hide');hud()}
function tap(i){if(!play||phase!=='input')return;pressed=i;pressT=.12;if(seq[input]===i){trail.push(i);score+=100+level*20+streak*6;streak++;input++;if(input>=seq.length){score+=200+level*40;level++;addNode();phase='clear';timer=.7;toast('CHAIN CLEARED')}}else{lives--;streak=0;trail=[];toast('WRONG NODE');if(lives<=0){end();return}phase='retry';timer=.75}hud()}
function update(dt){if(msgT>0){msgT-=dt;if(msgT<=0){msg='';$('toast').classList.remove('show')}}pressT=Math.max(0,pressT-dt);if(pressT<=0)pressed=-1;if(!play)return;if(phase==='clear'||phase==='retry'){timer-=dt;if(timer<=0)show();return}if(phase!=='show')return;timer-=dt;if(timer<=0){if(!lit){lit=true;timer=cfg().on}else{lit=false;idx++;if(idx>=seq.length){phase='input';idx=0;trail=[];hud()}else timer=cfg().gap}}}
function draw(){c.fillStyle='#050b14';c.fillRect(0,0,640,600);for(let x=0;x<640;x+=40){c.strokeStyle='#10273a';c.beginPath();c.moveTo(x,0);c.lineTo(x,600);c.stroke()}for(let y=0;y<600;y+=40){c.strokeStyle='#10273a';c.beginPath();c.moveTo(0,y);c.lineTo(640,y);c.stroke()}
c.strokeStyle='#274d67';c.lineWidth=3;for(let i=0;i<9;i++){const a=pos(i);for(const j of [i+1,i+3])if(j<9&&((j===i+1&&i%3<2)||j===i+3)){const b=pos(j);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()}}
const shown=phase==='show'?seq.slice(0,Math.min(seq.length,idx+(lit?1:0))):trail;if(shown.length>1){c.strokeStyle='#58dfff';c.lineWidth=7;c.shadowColor='#58dfff';c.shadowBlur=16;c.beginPath();shown.forEach((n,k)=>{const p=pos(n);if(k===0)c.moveTo(p.x,p.y);else c.lineTo(p.x,p.y)});c.stroke();c.shadowBlur=0}
for(let i=0;i<9;i++){const p=pos(i),active=(phase==='show'&&lit&&seq[idx]===i)||pressed===i;c.shadowColor=COLORS[i];c.shadowBlur=active?30:6;c.fillStyle=active?COLORS[i]:'#142233';c.beginPath();c.arc(p.x,p.y,46,0,Math.PI*2);c.fill();c.shadowBlur=0;c.strokeStyle=active?'#fff':'#355069';c.lineWidth=active?5:3;c.stroke();c.fillStyle=active?'#071018':'#a4b8cb';c.font='1000 22px system-ui';c.textAlign='center';c.fillText(String(i+1),p.x,p.y+7)}
c.fillStyle='#9fb4c9';c.font='900 13px system-ui';c.textAlign='center';c.fillText(phase==='show'?'WATCH THE GLOWING ROUTE':phase==='input'?'REPEAT THE ROUTE':'CIRCUIT HACKER',320,44)}
C.addEventListener('pointerdown',e=>{e.preventDefault();const r=C.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*640,y=(e.clientY-r.top)/r.height*600;let bi=-1,bd=1e9;for(let i=0;i<9;i++){const p=pos(i),d=(p.x-x)**2+(p.y-y)**2;if(d<bd){bd=d;bi=i}}if(bd<70*70)tap(bi)});addEventListener('keydown',e=>{const n=Number(e.key);if(n>=1&&n<=9)tap(n-1)});$('start').onclick=$('restart').onclick=reset;document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{if(!play)setDiff(b.dataset.diff)});let last=0;function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}setDiff(diff);hud();requestAnimationFrame(loop)})();