(()=>{'use strict';
const C=document.getElementById('game'),c=C.getContext('2d'),$=id=>document.getElementById(id);
const CFG={rookie:{speed:145,tol:48,credits:12},pro:{speed:180,tol:38,credits:10},hard:{speed:215,tol:30,credits:9},legend:{speed:250,tol:24,credits:8}};
const TYPES=[['🧸',80],['🎮',150],['💎',250],['🎧',180],['🏀',90],['🚗',120],['⭐',200],['🎁',110]];
let diff=localStorage.nd_claw_diff||'pro',play=false,score=0,used=0,combo=0,best=+(localStorage.nd_claw||0),x=320,y=82,dir=0,phase='idle',grab=null,prizes=[],msg='',msgT=0,home=320,chute=92,open=.9;
function cfg(){return CFG[diff]}function setDiff(d){if(!CFG[d])return;diff=d;localStorage.nd_claw_diff=d;document.querySelectorAll('[data-diff]').forEach(b=>b.classList.toggle('active',b.dataset.diff===d));hud()}
function toast(t){msg=t;msgT=.9;$('toast').textContent=t;$('toast').classList.add('show')}
function makePrizes(){prizes=[];for(let i=0;i<10;i++){const t=TYPES[Math.floor(Math.random()*TYPES.length)];prizes.push({x:115+(i%5)*102+(Math.random()-.5)*20,y:448+Math.floor(i/5)*62+(Math.random()-.5)*10,emoji:t[0],val:t[1],taken:false})}}
function hud(){$('score').textContent=score;$('round').textContent=used+'/'+cfg().credits;$('streak').textContent=combo;$('best').textContent=best;$('status').textContent=phase==='idle'?'POSITION CLAW · DROP WHEN CENTERED':phase==='down'?'DROPPING':'LIFTING / DELIVERING';$('progressFill').style.width=(used/cfg().credits*100)+'%';if(score>best){best=score;localStorage.nd_claw=best;$('best').textContent=best}}
function reset(){play=true;score=used=combo=0;x=home;y=82;dir=0;phase='idle';grab=null;open=.9;makePrizes();$('overlay').classList.add('hide');hud()}
function finish(){play=false;$('title').textContent='PRIZE RUN COMPLETE';$('msg').textContent='Score '+score+' · Best '+best+' · Prizes '+prizes.filter(p=>p.taken).length;$('start').textContent='PLAY AGAIN';$('overlay').classList.remove('hide')}
function drop(){if(play&&phase==='idle'){phase='down';grab=null;open=.9;hud()}}
function nearest(){let bp=null,bd=1e9;for(const p of prizes)if(!p.taken){const d=Math.abs(p.x-x);if(d<bd){bd=d;bp=p}}return{p:bp,d:bd}}
function update(dt){if(msgT>0){msgT-=dt;if(msgT<=0){msg='';$('toast').classList.remove('show')}}if(!play)return;const q=cfg();if(phase==='idle'){x=Math.max(72,Math.min(568,x+dir*q.speed*dt));open=.9}
else if(phase==='down'){y+=300*dt;open=Math.min(1,open+dt*1.8);if(y>=424){y=424;open=Math.max(.15,open-dt*7);const n=nearest();if(n.p&&n.d<=q.tol){grab=n.p;grab.taken=true;combo++;toast('GRABBED '+grab.emoji)}else{combo=0;toast('MISSED')}phase='up'}}
else if(phase==='up'){y-=305*dt;open=.2;if(grab){grab.x=x;grab.y=y+48}if(y<=82){y=82;phase=grab?'chute':'home'}}
else if(phase==='chute'){x-=260*dt;if(grab){grab.x=x;grab.y=y+48}if(x<=chute){x=chute;const gain=grab.val+combo*20;score+=gain;toast('+'+gain);grab=null;used++;phase='home'}}
else if(phase==='home'){const dx=home-x;if(Math.abs(dx)<4){x=home;phase='idle';if(used>=q.credits||prizes.every(p=>p.taken)){finish();return}}else x+=Math.sign(dx)*285*dt}hud()}
function draw(){const bg=c.createLinearGradient(0,0,0,600);bg.addColorStop(0,'#10283f');bg.addColorStop(1,'#08131f');c.fillStyle=bg;c.fillRect(0,0,640,600);c.fillStyle='#0d1c2a';c.fillRect(42,48,556,510);c.strokeStyle='#3e6886';c.lineWidth=5;c.strokeRect(42,48,556,510);c.fillStyle='#1b2d3e';c.fillRect(52,60,536,34);c.fillStyle='#ffd45f';for(let i=0;i<16;i++)c.fillRect(62+i*32,71,9,9);
c.fillStyle='#07111b';c.fillRect(52,430,536,118);c.fillStyle='#06101a';c.fillRect(48,486,112,72);c.fillStyle='#58dfff';c.fillRect(58,496,92,9);c.fillStyle='#9eb4c8';c.font='900 10px system-ui';c.textAlign='center';c.fillText('PRIZE CHUTE',104,542);
for(const p of prizes){if(p.taken&&p!==grab)continue;c.font='34px system-ui';c.fillText(p.emoji,p.x,p.y);c.fillStyle='#09131dcc';c.fillRect(p.x-24,p.y+16,48,16);c.fillStyle='#fff';c.font='900 9px system-ui';c.fillText('$'+p.val,p.x,p.y+28)}
c.strokeStyle='#d8e3ec';c.lineWidth=4;c.beginPath();c.moveTo(x,82);c.lineTo(x,y);c.stroke();c.fillStyle='#d8e3ec';c.fillRect(x-25,y,50,14);c.strokeStyle='#d8e3ec';c.lineWidth=5;c.beginPath();c.moveTo(x-18,y+14);c.lineTo(x-18-24*open,y+48);c.moveTo(x+18,y+14);c.lineTo(x+18+24*open,y+48);c.stroke();c.fillStyle='#9fb3c7';c.font='900 12px system-ui';c.fillText('CREDITS '+Math.max(0,cfg().credits-used)+' · CENTER THE CLAW OVER A PRIZE',320,32)}
function hold(btn,v){btn.onpointerdown=e=>{e.preventDefault();dir=v;try{btn.setPointerCapture(e.pointerId)}catch(_){}};const stop=()=>{if(dir===v)dir=0};btn.onpointerup=stop;btn.onpointercancel=stop;btn.onlostpointercapture=stop}hold($('left'),-1);hold($('right'),1);$('action').onclick=drop;$('start').onclick=$('restart').onclick=reset;document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{if(!play)setDiff(b.dataset.diff)});addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a'){e.preventDefault();dir=-1}if(k==='arrowright'||k==='d'){e.preventDefault();dir=1}if(e.code==='Space'){e.preventDefault();drop()}});addEventListener('keyup',e=>{const k=e.key.toLowerCase();if((k==='arrowleft'||k==='a')&&dir<0)dir=0;if((k==='arrowright'||k==='d')&&dir>0)dir=0});window.addEventListener('blur',()=>dir=0);let last=0;function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}setDiff(diff);hud();requestAnimationFrame(loop)})();