(()=>{'use strict';
const C=document.getElementById('game'),c=C.getContext('2d'),$=id=>document.getElementById(id);
const CFG={rookie:{speed:150,tol:44,credits:12},pro:{speed:185,tol:34,credits:10},hard:{speed:220,tol:27,credits:9},legend:{speed:260,tol:21,credits:8}};
const TYPES=[['🧸',80],['🎮',150],['💎',250],['🎧',180],['🏀',90],['🚗',120],['⭐',200],['🎁',110]];
let diff=localStorage.nd_claw_diff||'pro',playing=false,score=0,used=0,combo=0,best=+(localStorage.nd_claw||0),x=320,y=82,dir=0,phase='idle',grab=null,prizes=[],toastT=0,chuteX=82,homeX=320,pending=0;
function cfg(){return CFG[diff]}function setDiff(d){if(!CFG[d])return;diff=d;localStorage.nd_claw_diff=d;document.querySelectorAll('[data-diff]').forEach(b=>b.classList.toggle('active',b.dataset.diff===d));hud()}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');toastT=.8}
function makePrizes(){prizes=[];for(let i=0;i<10;i++){const t=TYPES[Math.floor(Math.random()*TYPES.length)];prizes.push({x:115+(i%5)*102+(Math.random()-.5)*24,y:455+Math.floor(i/5)*58+(Math.random()-.5)*12,emoji:t[0],val:t[1],taken:false})}}
function hud(){$('score').textContent=score;$('round').textContent=used+'/'+cfg().credits;$('streak').textContent=combo;$('best').textContent=best;$('status').textContent=phase==='idle'?'MOVE THE CLAW · DROP WHEN CENTERED':phase==='down'?'CLAW DROPPING':phase==='up'?'LIFTING':phase==='chute'?'DELIVERING PRIZE':'RESETTING';if(score>best){best=score;localStorage.nd_claw=best;$('best').textContent=best}$('progressFill').style.width=(used/cfg().credits*100)+'%'}
function reset(){playing=true;score=used=combo=0;x=homeX;y=82;dir=0;phase='idle';grab=null;pending=0;makePrizes();$('overlay').classList.add('hide');hud()}
function end(){playing=false;if(score>best){best=score;localStorage.nd_claw=best}$('title').textContent='PRIZE RUN COMPLETE';$('msg').textContent='Score '+score+' · Best '+best+' · Prizes '+prizes.filter(p=>p.taken).length;$('start').textContent='PLAY AGAIN';$('overlay').classList.remove('hide')}
function drop(){if(playing&&phase==='idle'){phase='down';grab=null;pending=0;hud()}}
function nearestPrize(){let bp=null,bd=1e9;for(const p of prizes)if(!p.taken){const d=Math.hypot(p.x-x,(p.y-20)-y);if(d<bd){bd=d;bp=p}}return{p:bp,d:bd}}
function update(dt){if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}if(!playing)return;const q=cfg();if(phase==='idle'){x=Math.max(70,Math.min(570,x+dir*q.speed*dt))}else if(phase==='down'){y+=300*dt;if(y>=430){y=430;const n=nearestPrize();if(n.p&&Math.abs(n.p.x-x)<=q.tol){grab=n.p;grab.taken=true;pending=grab.val;combo++;toast('GRABBED '+grab.emoji)}else{combo=0;toast('MISSED')}phase='up'}}else if(phase==='up'){y-=320*dt;if(grab){grab.x=x;grab.y=y+48}if(y<=82){y=82;if(grab)phase='chute';else{used++;phase='home'}}}else if(phase==='chute'){x-=250*dt;if(grab){grab.x=x;grab.y=y+48}if(x<=chuteX){x=chuteX;score+=pending+combo*20;toast('+'+(pending+combo*20));grab=null;pending=0;used++;phase='home'}}else if(phase==='home'){const dx=homeX-x;if(Math.abs(dx)<5){x=homeX;phase='idle';if(used>=q.credits||prizes.every(p=>p.taken)){end();return}}else x+=Math.sign(dx)*280*dt}hud()}
function draw(){c.fillStyle='#070c14';c.fillRect(0,0,640,600);const glass=c.createLinearGradient(0,0,0,600);glass.addColorStop(0,'#16304a');glass.addColorStop(1,'#0c1b29');c.fillStyle=glass;c.fillRect(42,48,556,510);c.strokeStyle='#3c607c';c.lineWidth=5;c.strokeRect(42,48,556,510);c.fillStyle='#09121c';c.fillRect(54,430,532,120);c.fillStyle='#203449';c.fillRect(52,58,536,32);c.fillStyle='#ffd45f';for(let i=0;i<16;i++)c.fillRect(62+i*32,68,9,9);c.fillStyle='#06101a';c.fillRect(48,488,108,70);c.fillStyle='#58dfff';c.fillRect(58,498,88,8);c.fillStyle='#9db3c7';c.font='900 10px system-ui';c.textAlign='center';c.fillText('PRIZE CHUTE',102,542);for(const p of prizes){if(p.taken&&p!==grab)continue;c.font='34px system-ui';c.fillText(p.emoji,p.x,p.y);c.fillStyle='#0b1520cc';c.fillRect(p.x-24,p.y+16,48,16);c.fillStyle='#fff';c.font='900 9px system-ui';c.fillText('$'+p.val,p.x,p.y+28)}c.strokeStyle='#d8e2ec';c.lineWidth=4;c.beginPath();c.moveTo(x,82);c.lineTo(x,y);c.stroke();c.fillStyle='#d8e2ec';c.fillRect(x-25,y,50,14);c.strokeStyle='#d8e2ec';c.lineWidth=5;c.beginPath();c.moveTo(x-20,y+14);c.lineTo(x-36,y+46);c.moveTo(x+20,y+14);c.lineTo(x+36,y+46);c.stroke();c.fillStyle='#9fb2c5';c.font='900 12px system-ui';c.fillText('CREDITS '+(cfg().credits-used)+' · ALIGN CENTER FOR A FAIR GRAB',320,32)}
function bindHold(btn,val){btn.onpointerdown=e=>{e.preventDefault();dir=val;try{btn.setPointerCapture(e.pointerId)}catch(_){} };const stop=()=>{if(dir===val)dir=0};btn.onpointerup=stop;btn.onpointercancel=stop;btn.onlostpointercapture=stop}bindHold($('left'),-1);bindHold($('right'),1);$('action').onclick=drop;$('start').onclick=$('restart').onclick=reset;
document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{if(!playing)setDiff(b.dataset.diff)});
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a'){e.preventDefault();dir=-1}if(k==='arrowright'||k==='d'){e.preventDefault();dir=1}if(e.code==='Space'){e.preventDefault();drop()}});
addEventListener('keyup',e=>{const k=e.key.toLowerCase();if((k==='arrowleft'||k==='a')&&dir<0)dir=0;if((k==='arrowright'||k==='d')&&dir>0)dir=0});
window.addEventListener('blur',()=>dir=0);let last=0;function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}setDiff(diff);hud();requestAnimationFrame(loop);
})();