(()=>{'use strict';
const C=document.getElementById('game'),c=C.getContext('2d'),$=id=>document.getElementById(id);
const COLORS=['#ff6078','#58dfff','#64e39b','#ffd45f'],NAMES=['RED','BLUE','GREEN','GOLD'],CFG={rookie:{speed:125,lives:4,gap:1.45},pro:{speed:165,lives:3,gap:1.18},hard:{speed:210,lives:3,gap:.98},legend:{speed:260,lives:2,gap:.82}};
let diff=localStorage.nd_color_diff||'pro',play=false,score=0,stage=1,streak=0,best=+(localStorage.nd_color||0),pick=1,lives=3,gates=[],spawn=0,elapsed=0,flash=0,msg='',msgT=0;
function cfg(){return CFG[diff]}function setDiff(d){if(!CFG[d])return;diff=d;localStorage.nd_color_diff=d;document.querySelectorAll('[data-diff]').forEach(b=>b.classList.toggle('active',b.dataset.diff===d));hud()}
function toast(t){msg=t;msgT=.7;$('toast').textContent=t;$('toast').classList.add('show')}
function hud(){$('score').textContent=score;$('round').textContent=stage;$('streak').textContent=streak;$('best').textContent=best;$('status').textContent='LIVES '+lives+' · ACTIVE '+NAMES[pick]+' · SPEED '+Math.round(cfg().speed+stage*7);$('progressFill').style.width=Math.min(100,(streak%10)*10)+'%';document.querySelectorAll('[data-color]').forEach(b=>b.classList.toggle('active',+b.dataset.color===pick));if(score>best){best=score;localStorage.nd_color=best;$('best').textContent=best}}
function reset(){play=true;score=streak=elapsed=0;stage=1;pick=1;lives=cfg().lives;gates=[];spawn=.45;flash=0;$('overlay').classList.add('hide');hud()}
function finish(){play=false;$('title').textContent='COLOR RUN OVER';$('msg').textContent='Score '+score+' · Best '+best+' · Stage '+stage;$('start').textContent='RUN AGAIN';$('overlay').classList.remove('hide')}
function choose(i){if(!play)return;pick=Math.max(0,Math.min(3,i));flash=.1;hud()}
function addGate(){let col=Math.floor(Math.random()*4);if(gates.length&&Math.random()<.3)col=(gates[gates.length-1].color+1+Math.floor(Math.random()*3))%4;gates.push({y:-90,color:col,checked:false});spawn=Math.max(.62,cfg().gap-stage*.015)}
function update(dt){if(msgT>0){msgT-=dt;if(msgT<=0){msg='';$('toast').classList.remove('show')}}if(!play)return;elapsed+=dt;stage=1+Math.floor(elapsed/8);flash=Math.max(0,flash-dt);spawn-=dt;if(spawn<=0)addGate();const speed=cfg().speed+stage*7;for(const g of gates){g.y+=speed*dt;if(!g.checked&&g.y>=455){g.checked=true;if(g.color===pick){score+=100+streak*18+stage*5;streak++;toast(streak>0&&streak%5===0?'🔥 '+streak+' STREAK':'MATCH')}else{lives--;streak=0;toast('WRONG · '+NAMES[g.color]+' NEEDED');if(lives<=0){finish();return}}}}gates=gates.filter(g=>g.y<650);hud()}
function draw(){const bg=c.createLinearGradient(0,0,0,600);bg.addColorStop(0,'#07101a');bg.addColorStop(1,'#11162b');c.fillStyle=bg;c.fillRect(0,0,640,600);c.strokeStyle='#ffffff0d';for(let y=30;y<600;y+=50){c.beginPath();c.moveTo(0,y);c.lineTo(640,y);c.stroke()}c.fillStyle='#172333';c.beginPath();c.moveTo(210,0);c.lineTo(430,0);c.lineTo(560,600);c.lineTo(80,600);c.closePath();c.fill();
for(const g of gates){const scale=.62+Math.max(0,g.y)/600*.58,w=300*scale,h=58*scale,x=320-w/2;c.globalAlpha=.18;c.fillStyle=COLORS[g.color];c.fillRect(x-18,g.y-10,w+36,h+20);c.globalAlpha=1;c.fillStyle=COLORS[g.color];c.fillRect(x,g.y,w,h);c.fillStyle='#07101a';c.font='1000 '+Math.round(18*scale)+'px system-ui';c.textAlign='center';c.fillText(NAMES[g.color],320,g.y+h*.64)}
c.fillStyle='#fff';c.fillRect(90,455,460,5);c.fillStyle=COLORS[pick];c.shadowColor=COLORS[pick];c.shadowBlur=flash?34:15;c.beginPath();c.arc(320,515,40,0,Math.PI*2);c.fill();c.shadowBlur=0;c.fillStyle='#fff';c.font='1000 14px system-ui';c.textAlign='center';c.fillText(NAMES[pick],320,520);c.fillStyle='#9fb2c6';c.font='900 12px system-ui';c.fillText('SWITCH BEFORE THE GATE HITS THE WHITE LINE',320,35)}
document.querySelectorAll('[data-color]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();choose(+b.dataset.color)});$('start').onclick=$('restart').onclick=reset;document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{if(!play)setDiff(b.dataset.diff)});addEventListener('keydown',e=>{const map={'1':0,'2':1,'3':2,'4':3,a:0,s:1,k:2,l:3},k=e.key.toLowerCase();if(k in map){e.preventDefault();choose(map[k])}});let last=0;function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}setDiff(diff);hud();requestAnimationFrame(loop)})();