(()=>{'use strict';
const C=document.getElementById('game'),c=C.getContext('2d'),$=id=>document.getElementById(id);
const COLORS=['#ff6078','#58dfff','#64e39b','#ffd45f'],NAMES=['RED','BLUE','GREEN','GOLD'];
const CFG={rookie:{speed:135,lives:4},pro:{speed:175,lives:3},hard:{speed:220,lives:3},legend:{speed:270,lives:2}};
let diff=localStorage.nd_color_diff||'pro',playing=false,score=0,round=1,streak=0,best=+(localStorage.nd_color||0),pick=1,lives=3,gates=[],spawn=0,elapsed=0,flash=0,toastT=0;
function cfg(){return CFG[diff]}function setDiff(d){if(!CFG[d])return;diff=d;localStorage.nd_color_diff=d;document.querySelectorAll('[data-diff]').forEach(b=>b.classList.toggle('active',b.dataset.diff===d));hud()}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');toastT=.65}
function hud(){$('score').textContent=score;$('round').textContent=round;$('streak').textContent=streak;$('best').textContent=best;$('status').textContent='LIVES '+lives+' · ACTIVE '+NAMES[pick]+' · SPEED '+Math.round(cfg().speed+round*7);document.querySelectorAll('[data-color]').forEach(b=>b.classList.toggle('active',+b.dataset.color===pick));if(score>best){best=score;localStorage.nd_color=best;$('best').textContent=best}$('progressFill').style.width=Math.min(100,(streak%10)*10)+'%'}
function reset(){playing=true;score=streak=elapsed=0;round=1;pick=1;lives=cfg().lives;gates=[];spawn=.4;flash=0;$('overlay').classList.add('hide');hud()}
function end(){playing=false;if(score>best){best=score;localStorage.nd_color=best}$('title').textContent='COLOR RUN OVER';$('msg').textContent='Score '+score+' · Best '+best+' · Round '+round;$('start').textContent='RUN AGAIN';$('overlay').classList.remove('hide')}
function choose(i){if(!playing)return;pick=Math.max(0,Math.min(3,i));flash=.08;hud()}
function spawnGate(){let col=Math.floor(Math.random()*4);if(gates.length&&Math.random()<.25)col=(gates[gates.length-1].color+1+Math.floor(Math.random()*3))%4;gates.push({y:-90,color:col,checked:false});spawn=Math.max(.72,1.28-round*.025)}
function update(dt){if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}if(!playing)return;elapsed+=dt;round=1+Math.floor(elapsed/9);flash=Math.max(0,flash-dt);spawn-=dt;if(spawn<=0)spawnGate();const speed=cfg().speed+round*7;for(const g of gates){g.y+=speed*dt;if(!g.checked&&g.y>=455){g.checked=true;if(g.color===pick){score+=100+streak*18+round*5;streak++;toast(streak&&streak%5===0?'🔥 '+streak+' STREAK':'MATCH')}else{lives--;streak=0;toast('WRONG COLOR');if(lives<=0){end();return}}}}gates=gates.filter(g=>g.y<650);hud()}
function draw(){const bg=c.createLinearGradient(0,0,0,600);bg.addColorStop(0,'#07101a');bg.addColorStop(1,'#11162b');c.fillStyle=bg;c.fillRect(0,0,640,600);c.strokeStyle='#ffffff0e';for(let y=30;y<600;y+=50){c.beginPath();c.moveTo(0,y);c.lineTo(640,y);c.stroke()}c.fillStyle='#172333';c.beginPath();c.moveTo(210,0);c.lineTo(430,0);c.lineTo(560,600);c.lineTo(80,600);c.closePath();c.fill();for(const g of gates){const scale=.65+g.y/600*.55,w=310*scale,h=60*scale,x=320-w/2;c.globalAlpha=.22;c.fillStyle=COLORS[g.color];c.fillRect(x-18,g.y-10,w+36,h+20);c.globalAlpha=1;c.fillStyle=COLORS[g.color];c.fillRect(x,g.y,w,h);c.fillStyle='#07101a';c.font='1000 '+Math.round(18*scale)+'px system-ui';c.textAlign='center';c.fillText(NAMES[g.color],320,g.y+h*.63)}c.fillStyle='#ffffff24';c.fillRect(90,455,460,5);c.fillStyle=COLORS[pick];c.shadowColor=COLORS[pick];c.shadowBlur=flash?30:14;c.beginPath();c.arc(320,515,38,0,Math.PI*2);c.fill();c.shadowBlur=0;c.fillStyle='#fff';c.font='1000 14px system-ui';c.textAlign='center';c.fillText(NAMES[pick],320,520);c.fillStyle='#9fb2c6';c.font='900 12px system-ui';c.fillText('MATCH THE GATE BEFORE IT CROSSES THE LINE',320,35)}
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>choose(+b.dataset.color));$('start').onclick=$('restart').onclick=reset;
document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{if(!playing)setDiff(b.dataset.diff)});
addEventListener('keydown',e=>{const map={'1':0,'2':1,'3':2,'4':3,a:0,s:1,k:2,l:3};const k=e.key.toLowerCase();if(k in map){e.preventDefault();choose(map[k])}});
let last=0;function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}setDiff(diff);hud();requestAnimationFrame(loop);
})();