(()=>{'use strict';
const C=document.getElementById('game'),c=C.getContext('2d'),$=id=>document.getElementById(id);
const CFG={rookie:{meter:.74,sweet:.22,read:.22},pro:{meter:1,sweet:.17,read:.38},hard:{meter:1.28,sweet:.13,read:.55},legend:{meter:1.58,sweet:.095,read:.7}};
const zones=[{x:175,y:155},{x:320,y:155},{x:465,y:155},{x:175,y:245},{x:320,y:245},{x:465,y:245},{x:175,y:330},{x:320,y:330},{x:465,y:330}];
let diff=localStorage.nd_penalty_diff||'pro',playing=false,score=0,shots=0,streak=0,best=+(localStorage.nd_penalty||0),zone=1,power=.2,pdir=1,keeperZone=4,shot=null,result='',resultT=0,toastT=0;
function cfg(){return CFG[diff]}
function setDiff(d){if(!CFG[d])return;diff=d;localStorage.nd_penalty_diff=d;document.querySelectorAll('[data-diff]').forEach(b=>b.classList.toggle('active',b.dataset.diff===d));hud()}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');toastT=.8}
function hud(){$('score').textContent=score;$('round').textContent=shots+'/10';$('streak').textContent=streak;$('best').textContent=best;$('status').textContent='TARGET '+(zone+1)+' · POWER '+Math.round(power*100)+'%'+(result?' · '+result:'');if(score>best){best=score;localStorage.nd_penalty=best;$('best').textContent=best}$('progressFill').style.width=(shots*10)+'%'}
function reset(){playing=true;score=shots=streak=0;zone=1;power=.2;pdir=1;keeperZone=4;shot=null;result='';resultT=0;$('overlay').classList.add('hide');hud()}
function finish(){playing=false;if(score>best){best=score;localStorage.nd_penalty=best}$('title').textContent='SHOOTOUT COMPLETE';$('msg').textContent='Score '+score+' · Best '+best+' · Goals '+(shots?Math.round(score/100):0);$('start').textContent='PLAY AGAIN';$('overlay').classList.remove('hide')}
function move(d){if(!playing||shot)return;zone=(zone+d+9)%9;hud()}
function chooseFromPoint(e){if(!playing||shot)return;const r=C.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*640,y=(e.clientY-r.top)/r.height*600;let bi=zone,bd=1e9;zones.forEach((z,i)=>{const d=(z.x-x)**2+(z.y-y)**2;if(d<bd){bd=d;bi=i}});if(y<390){zone=bi;hud()}}
function shoot(){if(!playing||shot)return;const q=cfg(),ideal=.72,pErr=Math.abs(power-ideal),accurate=pErr<=q.sweet;keeperZone=Math.random()<q.read?zone:Math.floor(Math.random()*9);const sameRow=Math.floor(keeperZone/3)===Math.floor(zone/3),sameCol=keeperZone%3===zone%3;const saved=accurate&&(keeperZone===zone||(sameRow&&sameCol&&Math.random()<.25));const goal=accurate&&!saved;result=goal?'GOAL!':saved?'SAVED':'MISS';if(goal){const corner=[0,2,6,8].includes(zone)?35:0;score+=120+corner+streak*22+Math.round((1-pErr)*35);streak++;toast(streak>=3?'🔥 '+streak+' GOAL STREAK':'⚽ GOAL')}else{streak=0;toast(result==='SAVED'?'🧤 SAVED':'↗ WIDE')}shots++;shot={t:0,d:.72,goal,saved,start:{x:320,y:510},target:{...zones[zone]}};resultT=1;hud()}
function update(dt){if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}if(!playing)return;if(resultT>0){resultT-=dt;if(resultT<=0)result=''}if(shot){shot.t+=dt;if(shot.t>=shot.d){shot=null;if(shots>=10){finish();return}}}else{power+=pdir*cfg().meter*dt;if(power>=1){power=1;pdir=-1}else if(power<=0){power=0;pdir=1}}hud()}
function drawNet(){c.strokeStyle='#ffffff2b';c.lineWidth=2;for(let x=95;x<=545;x+=50){c.beginPath();c.moveTo(x,95);c.lineTo(x,365);c.stroke()}for(let y=95;y<=365;y+=45){c.beginPath();c.moveTo(95,y);c.lineTo(545,y);c.stroke()}c.strokeStyle='#f5f7ff';c.lineWidth=8;c.strokeRect(85,85,470,290)}
function drawKeeper(){const z=zones[keeperZone],active=shot?Math.min(1,shot.t/shot.d*1.35):0,kx=320+(z.x-320)*active,ky=255+(z.y-255)*active*.45;c.save();c.translate(kx,ky);c.fillStyle='#ffd45f';c.fillRect(-25,-35,50,72);c.fillStyle='#f3c7a6';c.beginPath();c.arc(0,-50,15,0,Math.PI*2);c.fill();c.strokeStyle='#ffd45f';c.lineWidth=11;c.beginPath();c.moveTo(-18,-20);c.lineTo(-48,-4);c.moveTo(18,-20);c.lineTo(48,-4);c.stroke();c.restore()}
function draw(){c.fillStyle='#06101a';c.fillRect(0,0,640,600);const g=c.createLinearGradient(0,0,0,600);g.addColorStop(0,'#132849');g.addColorStop(.52,'#0d2231');g.addColorStop(.53,'#164d2e');g.addColorStop(1,'#0d351f');c.fillStyle=g;c.fillRect(0,0,640,600);
for(let i=0;i<50;i++){c.fillStyle=i%3===0?'#55dfff33':i%3===1?'#ffd45f33':'#ff607833';c.fillRect((i*83)%640,18+(i%5)*10,8,5)}
drawNet();
zones.forEach((z,i)=>{c.fillStyle=i===zone?'#59dfff25':'#ffffff08';c.fillRect(z.x-54,z.y-38,108,76);if(i===zone){c.strokeStyle='#59dfff';c.lineWidth=4;c.strokeRect(z.x-54,z.y-38,108,76)}});
drawKeeper();
let bx=320,by=510;if(shot){const p=Math.min(1,shot.t/shot.d),e=1-Math.pow(1-p,2);bx=shot.start.x+(shot.target.x-shot.start.x)*e;by=shot.start.y+(shot.target.y-shot.start.y)*e;c.globalAlpha=1-p*.35}c.fillStyle='#fff';c.beginPath();c.arc(bx,by,18,0,Math.PI*2);c.fill();c.globalAlpha=1;
c.fillStyle='#07131d';c.fillRect(100,548,440,24);c.fillStyle='#65e39b';c.fillRect(100+(0.72-cfg().sweet)*440,548,cfg().sweet*2*440,24);c.fillStyle='#fff';c.fillRect(100+power*440-4,541,8,38);c.fillStyle='#d6e3ef';c.font='900 12px system-ui';c.textAlign='center';c.fillText('TAP A GOAL ZONE OR USE ← → · SHOOT IN THE GREEN',320,42)}
C.addEventListener('pointerdown',e=>{e.preventDefault();chooseFromPoint(e)});
$('left').onclick=()=>move(-1);$('right').onclick=()=>move(1);$('action').onclick=shoot;$('start').onclick=$('restart').onclick=reset;
document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{if(!playing)setDiff(b.dataset.diff)});
addEventListener('keydown',e=>{if(['ArrowLeft','a','ArrowRight','d',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')move(-1);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')move(1);if(e.code==='Space')shoot()});
let last=0;function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}setDiff(diff);hud();requestAnimationFrame(loop);
})();