(()=>{'use strict';
const C=document.getElementById('game'),c=C.getContext('2d'),$=id=>document.getElementById(id);
const CFG={rookie:{meter:.72,sweet:.24,read:.18},pro:{meter:.95,sweet:.18,read:.34},hard:{meter:1.22,sweet:.13,read:.52},legend:{meter:1.55,sweet:.09,read:.68}};
const Z=[{x:175,y:150},{x:320,y:150},{x:465,y:150},{x:175,y:235},{x:320,y:235},{x:465,y:235},{x:175,y:320},{x:320,y:320},{x:465,y:320}];
let diff=localStorage.nd_penalty_diff||'pro',play=false,score=0,shots=0,streak=0,best=+(localStorage.nd_penalty||0),zone=4,power=.18,pdir=1,keeper=4,shot=null,particles=[],msg='',msgT=0;
function cfg(){return CFG[diff]}function setDiff(d){if(!CFG[d])return;diff=d;localStorage.nd_penalty_diff=d;document.querySelectorAll('[data-diff]').forEach(b=>b.classList.toggle('active',b.dataset.diff===d));hud()}
function hud(){$('score').textContent=score;$('round').textContent=shots+'/10';$('streak').textContent=streak;$('best').textContent=best;$('status').textContent='ZONE '+(zone+1)+' · POWER '+Math.round(power*100)+'%'+(msg?' · '+msg:'');$('progressFill').style.width=(shots*10)+'%';if(score>best){best=score;localStorage.nd_penalty=best;$('best').textContent=best}}
function toast(t){msg=t;msgT=.9;$('toast').textContent=t;$('toast').classList.add('show')}
function reset(){play=true;score=shots=streak=0;zone=4;power=.18;pdir=1;keeper=4;shot=null;particles=[];msg='';$('overlay').classList.add('hide');hud()}
function finish(){play=false;$('title').textContent='SHOOTOUT COMPLETE';$('msg').textContent='Score '+score+' · Best '+best+' · Goals '+Math.floor(score/100);$('start').textContent='PLAY AGAIN';$('overlay').classList.remove('hide')}
function move(d){if(!play||shot)return;zone=(zone+d+9)%9;hud()}
function pick(e){if(!play||shot)return;const r=C.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*640,y=(e.clientY-r.top)/r.height*600;if(y>390)return;let bi=zone,bd=1e9;Z.forEach((p,i)=>{const q=(p.x-x)**2+(p.y-y)**2;if(q<bd){bd=q;bi=i}});zone=bi;hud()}
function shoot(){if(!play||shot)return;const q=cfg(),err=Math.abs(power-.74),accurate=err<=q.sweet;keeper=Math.random()<q.read?zone:Math.floor(Math.random()*9);let save=false;if(accurate){const same=keeper===zone,near=Math.abs((keeper%3)-(zone%3))<=1&&Math.abs(Math.floor(keeper/3)-Math.floor(zone/3))<=1;save=same||(near&&Math.random()<.18+q.read*.2)}
const goal=accurate&&!save;shots++;if(goal){score+=120+([0,2,6,8].includes(zone)?35:0)+streak*20+Math.round((1-err)*30);streak++;toast(streak>=3?'🔥 '+streak+' IN A ROW':'⚽ GOAL')}else{streak=0;toast(save?'🧤 SAVED':'↗ MISS')}
shot={t:0,d:.68,goal,save,sx:320,sy:515,tx:Z[zone].x,ty:Z[zone].y};for(let i=0;i<18;i++)particles.push({x:320,y:515,vx:(Math.random()-.5)*90,vy:-40-Math.random()*80,t:.6+Math.random()*.3});hud()}
function update(dt){if(msgT>0){msgT-=dt;if(msgT<=0){msg='';$('toast').classList.remove('show')}}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=120*dt;p.t-=dt}particles=particles.filter(p=>p.t>0);if(!play)return;if(shot){shot.t+=dt;if(shot.t>=shot.d){shot=null;if(shots>=10){finish();return}}}else{power+=pdir*cfg().meter*dt;if(power>=1){power=1;pdir=-1}else if(power<=0){power=0;pdir=1}}hud()}
function net(){c.strokeStyle='#ffffff26';c.lineWidth=2;for(let x=95;x<=545;x+=50){c.beginPath();c.moveTo(x,88);c.lineTo(x,365);c.stroke()}for(let y=90;y<=365;y+=46){c.beginPath();c.moveTo(88,y);c.lineTo(552,y);c.stroke()}c.strokeStyle='#fff';c.lineWidth=8;c.strokeRect(82,82,476,292)}
function draw(){const g=c.createLinearGradient(0,0,0,600);g.addColorStop(0,'#101d3b');g.addColorStop(.5,'#10283a');g.addColorStop(.51,'#174c2d');g.addColorStop(1,'#0b321e');c.fillStyle=g;c.fillRect(0,0,640,600);for(let i=0;i<40;i++){c.fillStyle=i%2?'#58dfff22':'#ffd45f22';c.fillRect((i*83)%640,14+(i%4)*8,9,5)}net();
Z.forEach((p,i)=>{c.fillStyle=i===zone?'#58dfff22':'#ffffff07';c.fillRect(p.x-53,p.y-36,106,72);if(i===zone){c.strokeStyle='#58dfff';c.lineWidth=4;c.strokeRect(p.x-53,p.y-36,106,72)}});
const kp=Z[keeper],kprog=shot?Math.min(1,shot.t/shot.d*1.35):0,kx=320+(kp.x-320)*kprog,ky=245+(kp.y-245)*kprog*.42;c.save();c.translate(kx,ky);c.fillStyle='#ffd45f';c.fillRect(-25,-32,50,68);c.fillStyle='#f1c3a0';c.beginPath();c.arc(0,-46,14,0,Math.PI*2);c.fill();c.strokeStyle='#ffd45f';c.lineWidth=10;c.beginPath();c.moveTo(-18,-15);c.lineTo(-48,-2);c.moveTo(18,-15);c.lineTo(48,-2);c.stroke();c.restore();
let bx=320,by=515;if(shot){const p=Math.min(1,shot.t/shot.d),e=1-Math.pow(1-p,2);bx=shot.sx+(shot.tx-shot.sx)*e;by=shot.sy+(shot.ty-shot.sy)*e;c.strokeStyle='#ffffff55';c.lineWidth=4;c.beginPath();c.moveTo(shot.sx,shot.sy);c.lineTo(bx,by);c.stroke()}c.fillStyle='#fff';c.beginPath();c.arc(bx,by,18,0,Math.PI*2);c.fill();
for(const p of particles){c.globalAlpha=Math.max(0,p.t);c.fillStyle='#8feaff';c.fillRect(p.x,p.y,3,3)}c.globalAlpha=1;
c.fillStyle='#08131d';c.fillRect(100,548,440,24);c.fillStyle='#64e39b';c.fillRect(100+(.74-cfg().sweet)*440,548,cfg().sweet*2*440,24);c.fillStyle='#fff';c.fillRect(100+power*440-4,540,8,40);c.fillStyle='#d7e4ef';c.font='900 12px system-ui';c.textAlign='center';c.fillText('PICK A ZONE · HIT THE GREEN · BEAT THE DIVE',320,42)}
C.addEventListener('pointerdown',e=>{e.preventDefault();pick(e)});$('left').onclick=()=>move(-1);$('right').onclick=()=>move(1);$('action').onclick=shoot;$('start').onclick=$('restart').onclick=reset;document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{if(!play)setDiff(b.dataset.diff)});addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a'){e.preventDefault();move(-1)}if(k==='arrowright'||k==='d'){e.preventDefault();move(1)}if(e.code==='Space'){e.preventDefault();shoot()}});let last=0;function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}setDiff(diff);hud();requestAnimationFrame(loop)})();